<a href="https://colab.research.google.com/github/jhanani14/DEEP_LEARNING/blob/main/1_DL_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# IMPORTING LIBRARIES

from numpy import array     #For array initialization
from numpy import random    #For randomly choosing numbers
from numpy import dot       #For doing dot product
from random import choice

In [2]:
# ACTIVATION FUNCTION

activationFn = lambda x: 0 if x < 0 else 1

In [3]:
# TRAINING DATASET

dataset = [
    (array([0,1,1]),0),            #array([x,y,b],e)
    (array([0,1,1]),1),            #x,y=Input
    (array([1,0,1]),1),            #b=bias
    (array([1,1,1]),1)             #e=Expected output to validate
]
print(dataset)

[(array([0, 1, 1]), 0), (array([0, 1, 1]), 1), (array([1, 0, 1]), 1), (array([1, 1, 1]), 1)]


In [4]:
# INITIALIZING RANDOM NUMBERS FOR WEIGHTS

weights = random.rand(3)
weights

array([0.32049474, 0.11567148, 0.2467279 ])

In [5]:
# INITIALIZING ADDITIONAL VARIABLES

r = 0.2        #learning rate
n = 100        #number of iterations

In [6]:
# TRAINING OUR MODEL

for j in range(n):
  x,expected = choice(dataset)           #random input set,includes repeated numbers
  print(x,expected)
  result = dot(weights, x)               # dot product of the input and the weight vectors
  err = expected-activationFn(result)
  weights += r * err * x                 #calculate the correction factor, added to weights to improve output in next iteration
  #If the expected value is bigger,the weights should be increased,and if expected value is smaller,the weights should be decreased

[0 1 1] 0
[1 0 1] 1
[0 1 1] 0
[1 1 1] 1
[1 0 1] 1
[1 0 1] 1
[1 1 1] 1
[1 0 1] 1
[1 0 1] 1
[1 1 1] 1
[0 1 1] 1
[0 1 1] 0
[0 1 1] 1
[0 1 1] 0
[0 1 1] 0
[0 1 1] 0
[0 1 1] 1
[1 1 1] 1
[0 1 1] 0
[0 1 1] 0
[1 0 1] 1
[1 0 1] 1
[1 0 1] 1
[0 1 1] 1
[1 0 1] 1
[1 1 1] 1
[0 1 1] 1
[1 1 1] 1
[1 1 1] 1
[1 1 1] 1
[1 0 1] 1
[0 1 1] 0
[1 0 1] 1
[0 1 1] 1
[0 1 1] 1
[1 1 1] 1
[1 1 1] 1
[1 1 1] 1
[1 1 1] 1
[1 1 1] 1
[1 0 1] 1
[1 0 1] 1
[0 1 1] 1
[1 1 1] 1
[0 1 1] 1
[0 1 1] 1
[0 1 1] 1
[1 0 1] 1
[0 1 1] 1
[0 1 1] 0
[1 1 1] 1
[1 0 1] 1
[0 1 1] 1
[1 0 1] 1
[0 1 1] 0
[0 1 1] 1
[1 0 1] 1
[1 0 1] 1
[0 1 1] 0
[0 1 1] 0
[1 0 1] 1
[1 1 1] 1
[0 1 1] 1
[0 1 1] 0
[0 1 1] 0
[1 1 1] 1
[0 1 1] 1
[1 1 1] 1
[1 1 1] 1
[1 0 1] 1
[1 1 1] 1
[1 0 1] 1
[1 0 1] 1
[0 1 1] 1
[0 1 1] 1
[0 1 1] 1
[0 1 1] 0
[1 1 1] 1
[0 1 1] 1
[1 1 1] 1
[1 0 1] 1
[1 1 1] 1
[0 1 1] 1
[0 1 1] 0
[0 1 1] 1
[0 1 1] 0
[1 1 1] 1
[1 1 1] 1
[0 1 1] 0
[1 0 1] 1
[1 1 1] 1
[0 1 1] 0
[1 1 1] 1
[1 0 1] 1
[1 0 1] 1
[0 1 1] 0
[1 0 1] 1
[0 1 1] 1
[1 1 1] 1
[1 0 1] 1


In [7]:
# EVALUATING MODEL

for x, _ in dataset:
  result = dot(x,weights)
  print("Input: {} ResultBAFn: {} ResultAFn: {}".format(x[:2], round(result,3), activationFn(result)))

Input: [0 1] ResultBAFn: 0.362 ResultAFn: 1
Input: [0 1] ResultBAFn: 0.362 ResultAFn: 1
Input: [1 0] ResultBAFn: 0.567 ResultAFn: 1
Input: [1 1] ResultBAFn: 0.683 ResultAFn: 1
