<a href="https://colab.research.google.com/github/jhanani14/DEEP_LEARNING/blob/main/2_DL_ActivationFunction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
# IMPORTING LIBRARIES

from numpy import array     #For array initialization
from numpy import random    #For randomly choosing numbers
from numpy import dot       #For doing dot product
from random import choice

In [19]:
# ACTIVATION FUNCTION

activationFn = lambda x: 0 if x < 0 else 1       #STEP Activation Function

In [20]:
# TRAINING DATASET

dataset = [
    (array([0,1,1]),0),            #array([x,y,b],e)
    (array([0,1,1]),1),            #x,y=Input
    (array([1,0,1]),1),            #b=bias
    (array([1,1,1]),1)             #e=Expected output to validate
]
print(dataset)

[(array([0, 1, 1]), 0), (array([0, 1, 1]), 1), (array([1, 0, 1]), 1), (array([1, 1, 1]), 1)]


In [21]:
# INITIALIZING RANDOM NUMBERS FOR WEIGHTS

weights = random.rand(3)
weights

array([0.62522349, 0.23622426, 0.44800975])

In [22]:
# INITIALIZING ADDITIONAL VARIABLES

r = 0.2        #learning rate
n = 100        #number of iterations

In [23]:
#TRAINING AND EVALUATING USING STEP ACTIVATION FUNCTION

activationFn = lambda x: 0 if x<0 else 1
for j in range(n):
  x,expected = choice(dataset)           #random input set,includes repeated numbers
  print(x,expected)
  result = dot(weights, x)               # dot product of the input and the weight vectors
  err = expected-activationFn(result)
  weights += r * err * x                 #calculate the correction factor, added to weights to improve output in next iteration
  #If the expected value is bigger,the weights should be increased,and if expected value is smaller,the weights should be decreased

  for x,_ in dataset:
    result = dot(x,weights)
    print("Input: {} ResultBAFn: {} ResultAFn: {}".format(x[:2], round(result,3), activationFn(result)))


[0 1 1] 0
Input: [0 1] ResultBAFn: 0.284 ResultAFn: 1
Input: [0 1] ResultBAFn: 0.284 ResultAFn: 1
Input: [1 0] ResultBAFn: 0.873 ResultAFn: 1
Input: [1 1] ResultBAFn: 0.909 ResultAFn: 1
[1 0 1] 1
Input: [0 1] ResultBAFn: 0.284 ResultAFn: 1
Input: [0 1] ResultBAFn: 0.284 ResultAFn: 1
Input: [1 0] ResultBAFn: 0.873 ResultAFn: 1
Input: [1 1] ResultBAFn: 0.909 ResultAFn: 1
[0 1 1] 0
Input: [0 1] ResultBAFn: -0.116 ResultAFn: 0
Input: [0 1] ResultBAFn: -0.116 ResultAFn: 0
Input: [1 0] ResultBAFn: 0.673 ResultAFn: 1
Input: [1 1] ResultBAFn: 0.509 ResultAFn: 1
[0 1 1] 0
Input: [0 1] ResultBAFn: -0.116 ResultAFn: 0
Input: [0 1] ResultBAFn: -0.116 ResultAFn: 0
Input: [1 0] ResultBAFn: 0.673 ResultAFn: 1
Input: [1 1] ResultBAFn: 0.509 ResultAFn: 1
[1 0 1] 1
Input: [0 1] ResultBAFn: -0.116 ResultAFn: 0
Input: [0 1] ResultBAFn: -0.116 ResultAFn: 0
Input: [1 0] ResultBAFn: 0.673 ResultAFn: 1
Input: [1 1] ResultBAFn: 0.509 ResultAFn: 1
[1 0 1] 1
Input: [0 1] ResultBAFn: -0.116 ResultAFn: 0
Input: [0

In [24]:
#TRAINING AND EVALUATING USING LINEAR ACTIVATION FUNCTION

activationFn = lambda x: x
for j in range(n):
  x,expected = choice(dataset)           #random input set,includes repeated numbers
  print(x,expected)
  result = dot(weights, x)               # dot product of the input and the weight vectors
  err = expected-activationFn(result)
  weights += r * err * x                 #calculate the correction factor, added to weights to improve output in next iteration

  for x,_ in dataset:
    result = dot(x,weights)
    print("Input: {} ResultBAFn: {} ResultAFn: {}".format(x[:2], round(result,3), activationFn(result)))

[1 0 1] 1
Input: [0 1] ResultBAFn: 0.31 ResultAFn: 0.3095873576400574
Input: [0 1] ResultBAFn: 0.31 ResultAFn: 0.3095873576400574
Input: [1 0] ResultBAFn: 0.924 ResultAFn: 0.9239399444575651
Input: [1 1] ResultBAFn: 0.96 ResultAFn: 0.9601642043439855
[1 0 1] 1
Input: [0 1] ResultBAFn: 0.325 ResultAFn: 0.32479936874854437
Input: [0 1] ResultBAFn: 0.325 ResultAFn: 0.32479936874854437
Input: [1 0] ResultBAFn: 0.954 ResultAFn: 0.954363966674539
Input: [1 1] ResultBAFn: 0.991 ResultAFn: 0.9905882265609595
[0 1 1] 0
Input: [0 1] ResultBAFn: 0.195 ResultAFn: 0.1948796212491266
Input: [0 1] ResultBAFn: 0.195 ResultAFn: 0.1948796212491266
Input: [1 0] ResultBAFn: 0.889 ResultAFn: 0.8894040929248301
Input: [1 1] ResultBAFn: 0.861 ResultAFn: 0.8606684790615418
[0 1 1] 1
Input: [0 1] ResultBAFn: 0.517 ResultAFn: 0.516927772749476
Input: [0 1] ResultBAFn: 0.517 ResultAFn: 0.516927772749476
Input: [1 0] ResultBAFn: 1.05 ResultAFn: 1.0504281686750048
Input: [1 1] ResultBAFn: 1.183 ResultAFn: 1.182716

In [25]:
#TRAINING AND EVALUATING USING SIGMOID ACTIVATION FUNCTION

import numpy as np
activationFn = lambda x: 1/(1+np.exp(-x))
err = []
for j in range(n):
  x,expected = choice(dataset)           #random input set,includes repeated numbers
  print(x,expected)
  result = dot(weights, x)               # dot product of the input and the weight vectors
  err = expected-activationFn(result)
  weights += r * err * x                 #calculate the correction factor, added to weights to improve output in next iteration

  for x,_ in dataset:
    result = dot(x,weights)
    print("Input: {} ResultBAFn: {} ResultAFn: {}".format(x[:2], round(result,3), activationFn(result)))

[1 1 1] 1
Input: [0 1] ResultBAFn: 0.708 ResultAFn: 0.6699656109327812
Input: [0 1] ResultBAFn: 0.708 ResultAFn: 0.6699656109327812
Input: [1 0] ResultBAFn: 1.204 ResultAFn: 0.7691849572136154
Input: [1 1] ResultBAFn: 1.363 ResultAFn: 0.7961774040835858
[1 1 1] 1
Input: [0 1] ResultBAFn: 0.79 ResultAFn: 0.6877365378860173
Input: [0 1] ResultBAFn: 0.79 ResultAFn: 0.6877365378860173
Input: [1 0] ResultBAFn: 1.285 ResultAFn: 0.783341062724637
Input: [1 1] ResultBAFn: 1.485 ResultAFn: 0.8153063763115052
[0 1 1] 0
Input: [0 1] ResultBAFn: 0.514 ResultAFn: 0.625852343895679
Input: [0 1] ResultBAFn: 0.514 ResultAFn: 0.625852343895679
Input: [1 0] ResultBAFn: 1.148 ResultAFn: 0.7590899178901838
Input: [1 1] ResultBAFn: 1.21 ResultAFn: 0.770258425011955
[0 1 1] 1
Input: [0 1] ResultBAFn: 0.664 ResultAFn: 0.6601859567081948
Input: [0 1] ResultBAFn: 0.664 ResultAFn: 0.6601859567081948
Input: [1 0] ResultBAFn: 1.223 ResultAFn: 0.772507774725538
Input: [1 1] ResultBAFn: 1.359 ResultAFn: 0.795667049

In [26]:
#TRAINING AND EVALUATING USING RELU ACTIVATION FUNCTION

activationFn = lambda x: 0 if x < 0  else x
for j in range(n):
  x,expected = choice(dataset)           #random input set,includes repeated numbers
  print(x,expected)
  result = dot(weights, x)               # dot product of the input and the weight vectors
  err = expected-activationFn(result)
  weights += r * err * x                 #calculate the correction factor, added to weights to improve output in next iteration

  for x,_ in dataset:
    result = dot(x,weights)
    print("Input: {} ResultBAFn: {} ResultAFn: {}".format(x[:2], round(result,3), activationFn(result)))

[0 1 1] 0
Input: [0 1] ResultBAFn: 0.135 ResultAFn: 0.13486754994708788
Input: [0 1] ResultBAFn: 0.135 ResultAFn: 0.13486754994708788
Input: [1 0] ResultBAFn: 2.382 ResultAFn: 2.381904158683804
Input: [1 1] ResultBAFn: 1.989 ResultAFn: 1.9889701900851962
[1 0 1] 1
Input: [0 1] ResultBAFn: -0.142 ResultAFn: 0
Input: [0 1] ResultBAFn: -0.142 ResultAFn: 0
Input: [1 0] ResultBAFn: 1.829 ResultAFn: 1.8291424952102822
Input: [1 1] ResultBAFn: 1.436 ResultAFn: 1.4362085266116746
[1 0 1] 1
Input: [0 1] ResultBAFn: -0.307 ResultAFn: 0
Input: [0 1] ResultBAFn: -0.307 ResultAFn: 0
Input: [1 0] ResultBAFn: 1.497 ResultAFn: 1.4974854971261693
Input: [1 1] ResultBAFn: 1.105 ResultAFn: 1.1045515285275618
[1 1 1] 1
Input: [0 1] ResultBAFn: -0.349 ResultAFn: 0
Input: [0 1] ResultBAFn: -0.349 ResultAFn: 0
Input: [1 0] ResultBAFn: 1.456 ResultAFn: 1.4556648857151444
Input: [1 1] ResultBAFn: 1.042 ResultAFn: 1.0418206114110247
[0 1 1] 1
Input: [0 1] ResultBAFn: 0.051 ResultAFn: 0.050837607757245995
Input:

In [27]:
#TRAINING AND EVALUATING USING SOFTMAX ACTIVATION FUNCTION - MULTI-CLASS CLASSIFICATION

activationFn = lambda x: np.exp(x) / np.sum(np.exp(x),axis=0)
err=[]
for j in range(n):
  x,expected = choice(dataset)           #random input set,includes repeated numbers
  print(x,expected)
  result = dot(weights, x)               # dot product of the input and the weight vectors
  err = expected-activationFn(result)
  weights += r * err * x                 #calculate the correction factor, added to weights to improve output in next iteration

  for x,_ in dataset:
    result = dot(x,weights)
    print("Input: {} ResultBAFn: {} ResultAFn: {}".format(x[:2], round(result,3), activationFn(result)))

[0 1 1] 0
Input: [0 1] ResultBAFn: 0.037 ResultAFn: 1.0
Input: [0 1] ResultBAFn: 0.037 ResultAFn: 1.0
Input: [1 0] ResultBAFn: 0.811 ResultAFn: 1.0
Input: [1 1] ResultBAFn: 0.624 ResultAFn: 1.0
[0 1 1] 0
Input: [0 1] ResultBAFn: -0.363 ResultAFn: 1.0
Input: [0 1] ResultBAFn: -0.363 ResultAFn: 1.0
Input: [1 0] ResultBAFn: 0.611 ResultAFn: 1.0
Input: [1 1] ResultBAFn: 0.224 ResultAFn: 1.0
[0 1 1] 1
Input: [0 1] ResultBAFn: -0.363 ResultAFn: 1.0
Input: [0 1] ResultBAFn: -0.363 ResultAFn: 1.0
Input: [1 0] ResultBAFn: 0.611 ResultAFn: 1.0
Input: [1 1] ResultBAFn: 0.224 ResultAFn: 1.0
[1 1 1] 1
Input: [0 1] ResultBAFn: -0.363 ResultAFn: 1.0
Input: [0 1] ResultBAFn: -0.363 ResultAFn: 1.0
Input: [1 0] ResultBAFn: 0.611 ResultAFn: 1.0
Input: [1 1] ResultBAFn: 0.224 ResultAFn: 1.0
[1 0 1] 1
Input: [0 1] ResultBAFn: -0.363 ResultAFn: 1.0
Input: [0 1] ResultBAFn: -0.363 ResultAFn: 1.0
Input: [1 0] ResultBAFn: 0.611 ResultAFn: 1.0
Input: [1 1] ResultBAFn: 0.224 ResultAFn: 1.0
[1 1 1] 1
Input: [0 1]